# Generated by Django 5.1.3 on 2024-11-26 11:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(4, message='Name must be at least 3 characters')])),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(25, message='Description must be at least 25 characters')])),
                ('taken', models.BooleanField(default=False)),
                ('salary_per_month', models.IntegerField(validators=[django.core.validators.MinValueValidator(800, message='Salary must be at least 800$')])),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
