# Generated by Django 5.1.3 on 2024-12-08 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_jobapplication_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='message',
            new_name='bio',
        ),
    ]
