# Generated by Django 5.1.3 on 2024-11-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('Looker', 'Looker'), ('Searcher', 'Searcher')], default=1),
            preserve_default=False,
        ),
    ]
