# Generated by Django 5.1.3 on 2024-12-08 12:22

import accounts.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='contact_number',
            field=models.TextField(default=8888888888, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(13), accounts.validators.only_numbers]),
            preserve_default=False,
        ),
    ]
