# Generated by Django 5.1.3 on 2024-12-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('Job Poster', 'Job Poster'), ('Freelancer', 'Freelancer'), ('Moderator', 'Moderator')]),
        ),
    ]
