# Generated by Django 5.1.3 on 2024-12-10 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_customuser_profileuser'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('jobs', '0006_rename_message_jobapplication_bio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileUser',
            new_name='CustomUser',
        ),
    ]
